@contentType = application/json
@backendUrl = localhost
@port = 8040
@url = http://{{backendUrl}}:{{port}}/


## submit order

POST {{url}}/api/register
Content-Type: {{contentType}}

{
    "name": "张三",
    "email": "390583019@qq.com",
    "mobile": "",
    "source": "test"
}





